# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_login(object):
    def setupUi(self, Form_login):
        Form_login.setObjectName("Form_login")
        Form_login.resize(1920, 1080)
        self.gridLayout = QtWidgets.QGridLayout(Form_login)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_1 = QtWidgets.QWidget(Form_login)
        self.widget_1.setObjectName("widget_1")
        self.labelll = QtWidgets.QLabel(self.widget_1)
        self.labelll.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        self.labelll.setStyleSheet("\n"
"\n"
"border-image: url(:/anh_demo/hinh_coppy_right.jpg);\n"
"/*border-top-left-radius :50px;*/\n"
"\n"
"")
        self.labelll.setText("")
        self.labelll.setScaledContents(False)
        self.labelll.setObjectName("labelll")
        self.label_222 = QtWidgets.QLabel(self.widget_1)
        self.label_222.setGeometry(QtCore.QRect(-1, -1, 1951, 1931))
        self.label_222.setStyleSheet("\n"
"background-color: rgba(0,0,0,120);\n"
"/*border-top-left-radius :50px;*/\n"
"\n"
"")
        self.label_222.setText("")
        self.label_222.setPixmap(QtGui.QPixmap("hinh_coppy_right.jpg"))
        self.label_222.setScaledContents(True)
        self.label_222.setObjectName("label_222")
        self.Button_dangnhap = QtWidgets.QPushButton(self.widget_1)
        self.Button_dangnhap.setGeometry(QtCore.QRect(720, 610, 501, 201))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.Button_dangnhap.setFont(font)
        self.Button_dangnhap.setStyleSheet("QPushButton#Button_dangnhap\n"
"{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(230, 230, 230, 220));\n"
"color:rgba(255, 255, 255, 200);\n"
"border-radius:20px;\n"
"}\n"
"QPushButton#Button_dangnhap:hover{\n"
"/*background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 84, 81, 226));*/\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0.348, y1:0.561727, x2:1, y2:0.54, stop:0.199005 rgba(13, 211, 218, 210), stop:1 rgba(220, 220, 220, 255));\n"
"}\n"
"QPushButton#Button_dangnhap:pressed{\n"
"\n"
" padding-left:5px;\n"
" padding-top:5px;\n"
"    \n"
"\n"
"\n"
"}")
        self.Button_dangnhap.setObjectName("Button_dangnhap")
        self.label_dangnhapp = QtWidgets.QLabel(self.widget_1)
        self.label_dangnhapp.setGeometry(QtCore.QRect(670, 120, 761, 131))
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.label_dangnhapp.setFont(font)
        self.label_dangnhapp.setStyleSheet("\n"
"color: rgba(255, 255, 255,220);\n"
"")
        self.label_dangnhapp.setObjectName("label_dangnhapp")
        self.lineEdit_dangnhap = QtWidgets.QLineEdit(self.widget_1)
        self.lineEdit_dangnhap.setGeometry(QtCore.QRect(680, 260, 590, 110))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_dangnhap.setFont(font)
        self.lineEdit_dangnhap.setStyleSheet("background-color:rgba(255, 255, 255, 200);\n"
"border-radius:15px;\n"
"border-bottom:2px solid rgba(46, 82, 101, 200);\n"
"color:rgba(0, 0, 0, 240);\n"
"padding-bottom:7px;")
        self.lineEdit_dangnhap.setObjectName("lineEdit_dangnhap")
        self.lineEdit_matkhau = QtWidgets.QLineEdit(self.widget_1)
        self.lineEdit_matkhau.setGeometry(QtCore.QRect(680, 419, 590, 110))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_matkhau.setFont(font)
        self.lineEdit_matkhau.setStyleSheet("background-color:rgba(255, 255, 255, 200);\n"
"border-radius:15px;\n"
"border-bottom:2px solid rgba(46, 82, 101, 200);\n"
"color:rgba(0, 0, 0, 240);\n"
"padding-bottom:7px;")
        self.lineEdit_matkhau.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_matkhau.setObjectName("lineEdit_matkhau")
        self.Button_quenmk = QtWidgets.QPushButton(self.widget_1)
        self.Button_quenmk.setGeometry(QtCore.QRect(820, 880, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Button_quenmk.setFont(font)
        self.Button_quenmk.setStyleSheet("QPushButton#Button_quenmk{\n"
"    \n"
"color:rgba(255, 255, 255, 200);\n"
"border:none;\n"
"}\n"
"/*QPushButton#Button_quenmk:hover{\n"
"color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 0, 255, 255), stop:1 rgba(0, 0, 255, 255));\n"
"}*/\n"
"QPushButton#Button_quenmk:pressed{\n"
"\n"
" padding-left:5px;\n"
" padding-top:5px;\n"
"    \n"
"\n"
"\n"
"}")
        self.Button_quenmk.setObjectName("Button_quenmk")
        self.Button_tat_login = QtWidgets.QPushButton(self.widget_1)
        self.Button_tat_login.setGeometry(QtCore.QRect(1860, 20, 31, 31))
        self.Button_tat_login.setStyleSheet("\n"
"border-radius:15px;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.Button_tat_login.setText("")
        self.Button_tat_login.setObjectName("Button_tat_login")
        self.gridLayout.addWidget(self.widget_1, 0, 0, 1, 1)

        self.retranslateUi(Form_login)
        QtCore.QMetaObject.connectSlotsByName(Form_login)

    def retranslateUi(self, Form_login):
        _translate = QtCore.QCoreApplication.translate
        Form_login.setWindowTitle(_translate("Form_login", "Form"))
        self.Button_dangnhap.setText(_translate("Form_login", "ĐĂNG NHẬP"))
        self.label_dangnhapp.setText(_translate("Form_login", "Xin chào, tôi là ROBOT..."))
        self.lineEdit_dangnhap.setPlaceholderText(_translate("Form_login", "Tên Đăng Nhập"))
        self.lineEdit_matkhau.setPlaceholderText(_translate("Form_login", "Mật Khẩu"))
        self.Button_quenmk.setText(_translate("Form_login", "Quên mật khẩu?"))
