# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_map.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_map(object):
    def setupUi(self, Form_map):
        Form_map.setObjectName("Form_map")
        Form_map.resize(1550, 830)
        Form_map.setMinimumSize(QtCore.QSize(1525, 804))
        Form_map.setMaximumSize(QtCore.QSize(1525, 804))
        self.frame = QtWidgets.QFrame(Form_map)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1525, 804))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 20px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.stackedWidget_map = QtWidgets.QStackedWidget(self.frame)
        self.stackedWidget_map.setGeometry(QtCore.QRect(11, 11, 1501, 727))
        self.stackedWidget_map.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(230, 230, 230);\n"
"\n"
"")
        self.stackedWidget_map.setObjectName("stackedWidget_map")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.stackedWidget_map.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget_map.addWidget(self.page_2)
        self.slider_1_map = QtWidgets.QSlider(self.frame)
        self.slider_1_map.setGeometry(QtCore.QRect(360, 741, 781, 51))
        self.slider_1_map.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.slider_1_map.setStyleSheet("QSlider::groove:horizontal { \n"
"background: rgb(100, 100, 100); height: 5px; border: none;\n"
"    \n"
"    \n"
" }\n"
"QSlider::handle:horizontal { background:rgb(0, 85, 255); border: 1px solid #00BFFF; width: 15px; margin: -80px 0; border-radius: 5px;\n"
"border: none; }\n"
"\n"
"QSlider{border: none;}\n"
"\n"
"\n"
"        ")
        self.slider_1_map.setOrientation(QtCore.Qt.Horizontal)
        self.slider_1_map.setObjectName("slider_1_map")
        self.Button_thoat = QtWidgets.QPushButton(self.frame)
        self.Button_thoat.setGeometry(QtCore.QRect(1400, 750, 112, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Button_thoat.setFont(font)
        self.Button_thoat.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(45, 154, 200);\n"
"color: rgb(255, 255, 255);")
        self.Button_thoat.setObjectName("Button_thoat")

        self.retranslateUi(Form_map)
        QtCore.QMetaObject.connectSlotsByName(Form_map)

    def retranslateUi(self, Form_map):
        _translate = QtCore.QCoreApplication.translate
        Form_map.setWindowTitle(_translate("Form_map", "Form"))
        self.Button_thoat.setText(_translate("Form_map", "THOÁT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form_map = QtWidgets.QWidget()
    ui = Ui_Form_map()
    ui.setupUi(Form_map)
    Form_map.show()
    sys.exit(app.exec_())
