# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_cho_giay_lat.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_cho_giay_lat(object):
    def setupUi(self, Form_cho_giay_lat):
        Form_cho_giay_lat.setObjectName("Form_cho_giay_lat")
        Form_cho_giay_lat.resize(890, 485)
        Form_cho_giay_lat.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.progressBar_2 = QtWidgets.QProgressBar(Form_cho_giay_lat)
        self.progressBar_2.setGeometry(QtCore.QRect(150, 180, 591, 91))
        self.progressBar_2.setStyleSheet("QProgressBar{\n"
"    \n"
"    background-color: rgb(250, 250, 250);\n"
"    color: rgb(0, 0, 0);\n"
"    border-style:none;\n"
"    border-radius:30px;\n"
"    text-align:center;\n"
"}\n"
"QProgressBar::chunk{\n"
"\n"
"    border-radius:30px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.348, y1:0.561727, x2:1, y2:0.54, stop:0.199005 rgba(13, 211, 218, 210), stop:1 rgba(255, 255, 255, 255));\n"
"    /*background-color: qlineargradient(spread:pad, x1:0, y1:0.517045, x2:0.851, y2:0.523, stop:0 rgba(27, 200, 44, 235), stop:1 rgba(158, 255, 178, 255));*/\n"
"    }")
        self.progressBar_2.setProperty("value", 24)
        self.progressBar_2.setObjectName("progressBar_2")
        self.label = QtWidgets.QLabel(Form_cho_giay_lat)
        self.label.setGeometry(QtCore.QRect(380, 300, 161, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Form_cho_giay_lat)
        QtCore.QMetaObject.connectSlotsByName(Form_cho_giay_lat)

    def retranslateUi(self, Form_cho_giay_lat):
        _translate = QtCore.QCoreApplication.translate
        Form_cho_giay_lat.setWindowTitle(_translate("Form_cho_giay_lat", "Form"))
        self.label.setText(_translate("Form_cho_giay_lat", "Loading..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form_cho_giay_lat = QtWidgets.QWidget()
    ui = Ui_Form_cho_giay_lat()
    ui.setupUi(Form_cho_giay_lat)
    Form_cho_giay_lat.show()
    sys.exit(app.exec_())
