# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_dv.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_ui_dv(object):
    def setupUi(self, Form_ui_dv):
        Form_ui_dv.setObjectName("Form_ui_dv")
        Form_ui_dv.resize(550, 250)
        Form_ui_dv.setStyleSheet("")
        self.frames = QtWidgets.QFrame(Form_ui_dv)
        self.frames.setGeometry(QtCore.QRect(5, 5, 540, 240))
        self.frames.setStyleSheet("background-color: rgb(255,255,255);\n"
"border-radius: 25px;")
        self.frames.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frames.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frames.setObjectName("frames")
        self.label_ui_dv = QtWidgets.QLabel(self.frames)
        self.label_ui_dv.setGeometry(QtCore.QRect(0, 30, 531, 60))
        self.label_ui_dv.setMinimumSize(QtCore.QSize(500, 30))
        self.label_ui_dv.setMaximumSize(QtCore.QSize(5000, 60))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_ui_dv.setFont(font)
        self.label_ui_dv.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";\n"
"border-radius: 20px;")
        self.label_ui_dv.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ui_dv.setObjectName("label_ui_dv")
        self.Btn_ui_xn_dv = QtWidgets.QPushButton(self.frames)
        self.Btn_ui_xn_dv.setGeometry(QtCore.QRect(330, 170, 191, 61))
        self.Btn_ui_xn_dv.setStyleSheet("QPushButton#Btn_ui_xn_dv{\n"
"     border-radius: 20px;\n"
"    font: 75 28pt \"MS Shell Dlg 2\";\n"
"    border: 1px solid rgb(230, 230, 230);\n"
"background-color: rgb(230, 230, 230);\n"
"\n"
"}\n"
"\n"
"QPushButton#Btn_ui_xn_dv:pressed{\n"
"padding-left :2px;\n"
"padding-top :2px;\n"
"\n"
"    background-color: rgb(58, 192, 255);\n"
"}\n"
"QPushButton#Btn_ui_xn_dv:checked {\n"
"background-color: rgb(58, 192, 255);\n"
"\n"
"}\n"
"\n"
"")
        self.Btn_ui_xn_dv.setObjectName("Btn_ui_xn_dv")

        self.retranslateUi(Form_ui_dv)
        QtCore.QMetaObject.connectSlotsByName(Form_ui_dv)

    def retranslateUi(self, Form_ui_dv):
        _translate = QtCore.QCoreApplication.translate
        Form_ui_dv.setWindowTitle(_translate("Form_ui_dv", "Form"))
        self.label_ui_dv.setText(_translate("Form_ui_dv", "Đang trong quá trình định vị.\n"
" Vui lòng giữ khoảng cách an toàn."))
        self.Btn_ui_xn_dv.setText(_translate("Form_ui_dv", "Xác nhận"))
