# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'from_trang_toa_do.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_show_toado(object):
    def setupUi(self, Form_show_toado):
        Form_show_toado.setObjectName("Form_show_toado")
        Form_show_toado.resize(1072, 541)
        Form_show_toado.setStyleSheet("")
        self.btn_close_toado = QtWidgets.QPushButton(Form_show_toado)
        self.btn_close_toado.setGeometry(QtCore.QRect(910, 470, 151, 51))
        self.btn_close_toado.setStyleSheet("QPushButton#btn_close_toado{\n"
"       border-radius: 15px;\n"
"    font: 75 17pt \"MS Shell Dlg 2\";\n"
"    \n"
"    /*border: 3px solid rgb(230, 230, 230);*/\n"
"    color: rgb(0, 0, 0);\n"
"\n"
"    \n"
"\n"
"    background-color: rgb(220, 220, 220);\n"
"}\n"
"QPushButton#btn_close_toado:pressed{\n"
"       border-radius: 15px;\n"
"    font: 75 17pt \"MS Shell Dlg 2\";\n"
"    \n"
"    /*border: 3px solid rgb(230, 230, 230);*/\n"
"    \n"
"    font: 75 20pt \"Ubuntu Condensed\";\n"
"    \n"
"    background-color: #3498db;\n"
"  color: white;           \n"
"   padding-left: 2px;       \n"
"  padding-top: 2px;\n"
"    \n"
"}")
        self.btn_close_toado.setObjectName("btn_close_toado")
        self.tableWidget_toado = QtWidgets.QTableWidget(Form_show_toado)
        self.tableWidget_toado.setGeometry(QtCore.QRect(10, 20, 1051, 430))
        self.tableWidget_toado.setStyleSheet("background: white")
        self.tableWidget_toado.setObjectName("tableWidget_toado")
        self.tableWidget_toado.setColumnCount(0)
        self.tableWidget_toado.setRowCount(0)
        self.terminal_toado = QtWidgets.QPlainTextEdit(Form_show_toado)
        self.terminal_toado.setGeometry(QtCore.QRect(10, 460, 891, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.terminal_toado.setFont(font)
        self.terminal_toado.setStyleSheet("background: white;\n"
"boder-radius:15p;")
        self.terminal_toado.setObjectName("terminal_toado")

        self.retranslateUi(Form_show_toado)
        QtCore.QMetaObject.connectSlotsByName(Form_show_toado)

    def retranslateUi(self, Form_show_toado):
        _translate = QtCore.QCoreApplication.translate
        Form_show_toado.setWindowTitle(_translate("Form_show_toado", "Form"))
        self.btn_close_toado.setText(_translate("Form_show_toado", "Close"))
