# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'from_tinh_trang_pin.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_status_pin(object):
    def setupUi(self, Form_status_pin):
        Form_status_pin.setObjectName("Form_status_pin")
        Form_status_pin.resize(550, 250)
        Form_status_pin.setStyleSheet("")
        self.frames = QtWidgets.QFrame(Form_status_pin)
        self.frames.setGeometry(QtCore.QRect(-6, -6, 581, 261))
        self.frames.setStyleSheet("background-color: rgb(255,255,255);\n"
"     border-radius: 5px;")
        self.frames.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frames.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frames.setObjectName("frames")
        self.label_thongbao_pin = QtWidgets.QLabel(self.frames)
        self.label_thongbao_pin.setGeometry(QtCore.QRect(40, 120, 500, 60))
        self.label_thongbao_pin.setMinimumSize(QtCore.QSize(500, 30))
        self.label_thongbao_pin.setMaximumSize(QtCore.QSize(5000, 60))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_thongbao_pin.setFont(font)
        self.label_thongbao_pin.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"border-radius: 20px;")
        self.label_thongbao_pin.setAlignment(QtCore.Qt.AlignCenter)
        self.label_thongbao_pin.setObjectName("label_thongbao_pin")
        self.label_phantram_pin = QtWidgets.QLabel(self.frames)
        self.label_phantram_pin.setGeometry(QtCore.QRect(40, 30, 181, 91))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_phantram_pin.setFont(font)
        self.label_phantram_pin.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.label_phantram_pin.setObjectName("label_phantram_pin")
        self.btn_sac_auto = QtWidgets.QPushButton(self.frames)
        self.btn_sac_auto.setGeometry(QtCore.QRect(380, 180, 151, 51))
        self.btn_sac_auto.setStyleSheet("QPushButton#btn_sac_auto{\n"
"       border-radius: 15px;\n"
"    font: 75 17pt \"MS Shell Dlg 2\";\n"
"    \n"
"    /*border: 3px solid rgb(230, 230, 230);*/\n"
"    color: rgb(0, 0, 0);\n"
"\n"
"    \n"
"\n"
"    background-color: rgb(220, 220, 220);\n"
"}\n"
"QPushButton#btn_sac_auto:pressed{\n"
"       border-radius: 15px;\n"
"    font: 75 17pt \"MS Shell Dlg 2\";\n"
"    \n"
"    /*border: 3px solid rgb(230, 230, 230);*/\n"
"    \n"
"    font: 75 20pt \"Ubuntu Condensed\";\n"
"    \n"
"    background-color: #3498db;\n"
"  color: white;           \n"
"   padding-left: 2px;       \n"
"  padding-top: 2px;\n"
"    \n"
"}")
        self.btn_sac_auto.setObjectName("btn_sac_auto")
        self.btn_xn_pin = QtWidgets.QPushButton(self.frames)
        self.btn_xn_pin.setGeometry(QtCore.QRect(220, 40, 151, 71))
        self.btn_xn_pin.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../images/low-battery_12193220.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_xn_pin.setIcon(icon)
        self.btn_xn_pin.setIconSize(QtCore.QSize(150, 150))
        self.btn_xn_pin.setObjectName("btn_xn_pin")

        self.retranslateUi(Form_status_pin)
        QtCore.QMetaObject.connectSlotsByName(Form_status_pin)

    def retranslateUi(self, Form_status_pin):
        _translate = QtCore.QCoreApplication.translate
        Form_status_pin.setWindowTitle(_translate("Form_status_pin", "Form"))
        self.label_thongbao_pin.setText(_translate("Form_status_pin", "Pin"))
        self.label_phantram_pin.setText(_translate("Form_status_pin", "Percent: 0%"))
        self.btn_sac_auto.setText(_translate("Form_status_pin", "Sạc tự động"))
