# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'from_trang_ID.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_show_ID(object):
    def setupUi(self, Form_show_ID):
        Form_show_ID.setObjectName("Form_show_ID")
        Form_show_ID.resize(1072, 541)
        Form_show_ID.setStyleSheet("")
        self.btn_close_ID = QtWidgets.QPushButton(Form_show_ID)
        self.btn_close_ID.setGeometry(QtCore.QRect(910, 470, 151, 51))
        self.btn_close_ID.setStyleSheet("QPushButton#btn_close_ID{\n"
"       border-radius: 15px;\n"
"    font: 75 17pt \"MS Shell Dlg 2\";\n"
"    \n"
"    /*border: 3px solid rgb(230, 230, 230);*/\n"
"    color: rgb(0, 0, 0);\n"
"\n"
"    \n"
"\n"
"    background-color: rgb(220, 220, 220);\n"
"}\n"
"QPushButton#btn_close_ID:pressed{\n"
"       border-radius: 15px;\n"
"    font: 75 17pt \"MS Shell Dlg 2\";\n"
"    \n"
"    /*border: 3px solid rgb(230, 230, 230);*/\n"
"    \n"
"    font: 75 20pt \"Ubuntu Condensed\";\n"
"    \n"
"    background-color: #3498db;\n"
"  color: white;           \n"
"   padding-left: 2px;       \n"
"  padding-top: 2px;\n"
"    \n"
"}")
        self.btn_close_ID.setObjectName("btn_close_ID")
        self.tableWidget_ID = QtWidgets.QTableWidget(Form_show_ID)
        self.tableWidget_ID.setGeometry(QtCore.QRect(10, 20, 1051, 430))
        self.tableWidget_ID.setStyleSheet("background: white")
        self.tableWidget_ID.setObjectName("tableWidget_ID")
        self.tableWidget_ID.setColumnCount(0)
        self.tableWidget_ID.setRowCount(0)
        self.terminal_ID = QtWidgets.QPlainTextEdit(Form_show_ID)
        self.terminal_ID.setGeometry(QtCore.QRect(10, 460, 891, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.terminal_ID.setFont(font)
        self.terminal_ID.setStyleSheet("background: white;\n"
"boder-radius:15p;")
        self.terminal_ID.setObjectName("terminal_ID")

        self.retranslateUi(Form_show_ID)
        QtCore.QMetaObject.connectSlotsByName(Form_show_ID)

    def retranslateUi(self, Form_show_ID):
        _translate = QtCore.QCoreApplication.translate
        Form_show_ID.setWindowTitle(_translate("Form_show_ID", "Form"))
        self.btn_close_ID.setText(_translate("Form_show_ID", "Close"))
