# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'from_error_cam.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_error_cam(object):
    def setupUi(self, Form_error_cam):
        Form_error_cam.setObjectName("Form_error_cam")
        Form_error_cam.resize(550, 250)
        Form_error_cam.setStyleSheet("")
        self.frames = QtWidgets.QFrame(Form_error_cam)
        self.frames.setGeometry(QtCore.QRect(5, 5, 540, 240))
        self.frames.setStyleSheet("background-color: rgb(255,255,255);\n"
"border-radius: 25px;")
        self.frames.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frames.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frames.setObjectName("frames")
        self.label_themvao = QtWidgets.QLabel(self.frames)
        self.label_themvao.setGeometry(QtCore.QRect(10, 10, 501, 60))
        self.label_themvao.setMinimumSize(QtCore.QSize(500, 30))
        self.label_themvao.setMaximumSize(QtCore.QSize(5000, 60))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_themvao.setFont(font)
        self.label_themvao.setStyleSheet("font: 16pt \"MS Shell Dlg 2\"")
        self.label_themvao.setAlignment(QtCore.Qt.AlignCenter)
        self.label_themvao.setObjectName("label_themvao")
        self.pushButton = QtWidgets.QPushButton(self.frames)
        self.pushButton.setGeometry(QtCore.QRect(150, 80, 190, 100))
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../ROBOT_HD/images/warning.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(80, 80))
        self.pushButton.setObjectName("pushButton")
        self.btn_error_cam = QtWidgets.QPushButton(self.frames)
        self.btn_error_cam.setGeometry(QtCore.QRect(420, 180, 110, 50))
        self.btn_error_cam.setMinimumSize(QtCore.QSize(100, 50))
        self.btn_error_cam.setMaximumSize(QtCore.QSize(150, 50))
        self.btn_error_cam.setStyleSheet("QPushButton#btn_error_cam{\n"
"     border-radius: 10px;\n"
"    font: 75 16pt \"MS Shell Dlg 2\";\n"
"    border: 1px solid rgb(230, 230, 230);\n"
"    background-color: rgb(230, 230, 230);\n"
"\n"
"}\n"
"\n"
"QPushButton#btn_error_cam:pressed{\n"
"padding-left :2px;\n"
"padding-top :2px;\n"
"\n"
"    background-color: rgb(58, 192, 240);\n"
"}\n"
"QPushButton#btn_error_cam:checked {\n"
"background-color: rgb(58, 192, 255);\n"
"\n"
"}\n"
"")
        self.btn_error_cam.setIconSize(QtCore.QSize(80, 80))
        self.btn_error_cam.setObjectName("btn_error_cam")

        self.retranslateUi(Form_error_cam)
        QtCore.QMetaObject.connectSlotsByName(Form_error_cam)

    def retranslateUi(self, Form_error_cam):
        _translate = QtCore.QCoreApplication.translate
        Form_error_cam.setWindowTitle(_translate("Form_error_cam", "Form"))
        self.label_themvao.setText(_translate("Form_error_cam", "Nhận dạng vị trí home bị lỗi.\n"
" Vui lòng điều chỉnh vị trí . "))
        self.btn_error_cam.setText(_translate("Form_error_cam", "Xác nhận"))
