# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_login(object):
    def setupUi(self, Form_login):
        Form_login.setObjectName("Form_login")
        Form_login.resize(1920, 1080)
        self.gridLayout = QtWidgets.QGridLayout(Form_login)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_1 = QtWidgets.QWidget(Form_login)
        self.widget_1.setObjectName("widget_1")
        self.pushButton = QtWidgets.QPushButton(self.widget_1)
        self.pushButton.setGeometry(QtCore.QRect(760, 130, 89, 25))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.widget_1, 0, 0, 1, 1)

        self.retranslateUi(Form_login)
        QtCore.QMetaObject.connectSlotsByName(Form_login)

    def retranslateUi(self, Form_login):
        _translate = QtCore.QCoreApplication.translate
        Form_login.setWindowTitle(_translate("Form_login", "Form"))
        self.pushButton.setText(_translate("Form_login", "PushButton"))
