# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'from_xn_chuphinh.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_xn_chupanh(object):
    def setupUi(self, Form_xn_chupanh):
        Form_xn_chupanh.setObjectName("Form_xn_chupanh")
        Form_xn_chupanh.resize(829, 243)
        Form_xn_chupanh.setStyleSheet("")
        self.frames = QtWidgets.QFrame(Form_xn_chupanh)
        self.frames.setGeometry(QtCore.QRect(5, 5, 821, 231))
        self.frames.setStyleSheet("background-color: rgb(255,255,255);\n"
"border-radius: 25px;")
        self.frames.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frames.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frames.setObjectName("frames")
        self.label_themvao = QtWidgets.QLabel(self.frames)
        self.label_themvao.setGeometry(QtCore.QRect(10, 50, 801, 60))
        self.label_themvao.setMinimumSize(QtCore.QSize(500, 30))
        self.label_themvao.setMaximumSize(QtCore.QSize(5000, 60))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_themvao.setFont(font)
        self.label_themvao.setStyleSheet("font: 13pt \"MS Shell Dlg 2\"")
        self.label_themvao.setAlignment(QtCore.Qt.AlignCenter)
        self.label_themvao.setObjectName("label_themvao")
        self.btn_finish_camera = QtWidgets.QPushButton(self.frames)
        self.btn_finish_camera.setGeometry(QtCore.QRect(340, 150, 150, 50))
        self.btn_finish_camera.setMinimumSize(QtCore.QSize(100, 50))
        self.btn_finish_camera.setMaximumSize(QtCore.QSize(150, 50))
        self.btn_finish_camera.setStyleSheet("QPushButton#btn_finish_camera{\n"
"     border-radius: 10px;\n"
"    font: 75 16pt \"MS Shell Dlg 2\";\n"
"    border: 1px solid rgb(230, 230, 230);\n"
"    background-color: rgb(230, 230, 230);\n"
"\n"
"}\n"
"\n"
"QPushButton#btn_finish_camera:pressed{\n"
"padding-left :2px;\n"
"padding-top :2px;\n"
"\n"
"    background-color: rgb(58, 192, 240);\n"
"}\n"
"QPushButton#btn_finish_camera:checked {\n"
"background-color: rgb(58, 192, 255);\n"
"\n"
"}\n"
"")
        self.btn_finish_camera.setIconSize(QtCore.QSize(80, 80))
        self.btn_finish_camera.setObjectName("btn_finish_camera")

        self.retranslateUi(Form_xn_chupanh)
        QtCore.QMetaObject.connectSlotsByName(Form_xn_chupanh)

    def retranslateUi(self, Form_xn_chupanh):
        _translate = QtCore.QCoreApplication.translate
        Form_xn_chupanh.setWindowTitle(_translate("Form_xn_chupanh", "Form"))
        self.label_themvao.setText(_translate("Form_xn_chupanh", " Vui lòng căn chỉnh khuông mặt vào khung hình, nhấn nút chụp ảnh và đợi 10S"))
        self.btn_finish_camera.setText(_translate("Form_xn_chupanh", "Chụp ảnh"))
