# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_login(object):
    def setupUi(self, MainWindow_login):
        MainWindow_login.setObjectName("MainWindow_login")
        MainWindow_login.resize(1911, 1000)
        self.centralwidget = QtWidgets.QWidget(MainWindow_login)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_dn_login = QtWidgets.QPushButton(self.centralwidget)
        self.btn_dn_login.setGeometry(QtCore.QRect(790, 680, 341, 131))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.btn_dn_login.setFont(font)
        self.btn_dn_login.setStyleSheet("QPushButton#btn_dn_login\n"
"{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(230, 230, 230, 220));\n"
"color:rgba(255, 255, 255, 200);\n"
"border-radius:20px;\n"
"}\n"
"QPushButton#btn_dn_login:hover{\n"
"/*background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 84, 81, 226));*/\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0.348, y1:0.561727, x2:1, y2:0.54, stop:0.199005 rgba(13, 211, 218, 210), stop:1 rgba(220, 220, 220, 255));\n"
"}\n"
"QPushButton#btn_dn_login:pressed{\n"
"\n"
" padding-left:5px;\n"
" padding-top:5px;\n"
"    \n"
"\n"
"\n"
"}")
        self.btn_dn_login.setObjectName("btn_dn_login")
        self.label_222 = QtWidgets.QLabel(self.centralwidget)
        self.label_222.setGeometry(QtCore.QRect(10, -30, 1951, 1931))
        self.label_222.setStyleSheet("\n"
"background-color: rgba(0,0,0,120);\n"
"/*border-top-left-radius :50px;*/\n"
"\n"
"")
        self.label_222.setText("")
        self.label_222.setPixmap(QtGui.QPixmap("hinh_coppy_right.jpg"))
        self.label_222.setScaledContents(True)
        self.label_222.setObjectName("label_222")
        self.label_dangnhapp = QtWidgets.QLabel(self.centralwidget)
        self.label_dangnhapp.setGeometry(QtCore.QRect(630, 170, 761, 131))
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.label_dangnhapp.setFont(font)
        self.label_dangnhapp.setStyleSheet("\n"
"color: rgba(255, 255, 255,220);\n"
"")
        self.label_dangnhapp.setObjectName("label_dangnhapp")
        self.lineEdit_dangnhap = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_dangnhap.setGeometry(QtCore.QRect(650, 340, 590, 110))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_dangnhap.setFont(font)
        self.lineEdit_dangnhap.setStyleSheet("background-color:rgba(255, 255, 255, 200);\n"
"border-radius:15px;\n"
"border-bottom:2px solid rgba(46, 82, 101, 200);\n"
"color:rgba(0, 0, 0, 240);\n"
"padding-bottom:7px;")
        self.lineEdit_dangnhap.setObjectName("lineEdit_dangnhap")
        self.lineEdit_matkhau = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_matkhau.setGeometry(QtCore.QRect(650, 490, 590, 110))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_matkhau.setFont(font)
        self.lineEdit_matkhau.setStyleSheet("background-color:rgba(255, 255, 255, 200);\n"
"border-radius:15px;\n"
"border-bottom:2px solid rgba(46, 82, 101, 200);\n"
"color:rgba(0, 0, 0, 240);\n"
"padding-bottom:7px;")
        self.lineEdit_matkhau.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_matkhau.setObjectName("lineEdit_matkhau")
        self.Button_quenmk = QtWidgets.QPushButton(self.centralwidget)
        self.Button_quenmk.setGeometry(QtCore.QRect(820, 860, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Button_quenmk.setFont(font)
        self.Button_quenmk.setStyleSheet("QPushButton#Button_quenmk{\n"
"    \n"
"color:rgba(255, 255, 255, 200);\n"
"border:none;\n"
"}\n"
"/*QPushButton#Button_quenmk:hover{\n"
"color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 0, 255, 255), stop:1 rgba(0, 0, 255, 255));\n"
"}*/\n"
"QPushButton#Button_quenmk:pressed{\n"
"\n"
" padding-left:5px;\n"
" padding-top:5px;\n"
"    \n"
"\n"
"\n"
"}")
        self.Button_quenmk.setObjectName("Button_quenmk")
        self.Button_tat_login = QtWidgets.QPushButton(self.centralwidget)
        self.Button_tat_login.setGeometry(QtCore.QRect(1870, 10, 31, 31))
        self.Button_tat_login.setStyleSheet("\n"
"border-radius:15px;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.Button_tat_login.setText("")
        self.Button_tat_login.setObjectName("Button_tat_login")
        self.label_222.raise_()
        self.label_dangnhapp.raise_()
        self.Button_tat_login.raise_()
        self.lineEdit_dangnhap.raise_()
        self.lineEdit_matkhau.raise_()
        self.btn_dn_login.raise_()
        self.Button_quenmk.raise_()
        MainWindow_login.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow_login)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1911, 22))
        self.menubar.setObjectName("menubar")
        MainWindow_login.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow_login)
        self.statusbar.setObjectName("statusbar")
        MainWindow_login.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow_login)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_login)

    def retranslateUi(self, MainWindow_login):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_login.setWindowTitle(_translate("MainWindow_login", "MainWindow"))
        self.btn_dn_login.setText(_translate("MainWindow_login", "Đăng nhập"))
        self.label_dangnhapp.setText(_translate("MainWindow_login", "Xin chào, tôi là ROBOT ASR"))
        self.lineEdit_dangnhap.setPlaceholderText(_translate("MainWindow_login", "Tên Đăng Nhập"))
        self.lineEdit_matkhau.setPlaceholderText(_translate("MainWindow_login", "Mật Khẩu"))
        self.Button_quenmk.setText(_translate("MainWindow_login", "Quên mật khẩu?"))
