# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'page_waiting.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UI_waiting(object):
    def setupUi(self, UI_waiting):
        UI_waiting.setObjectName("UI_waiting")
        UI_waiting.resize(1800, 1000)
        self.centralwidget = QtWidgets.QWidget(UI_waiting)
        self.centralwidget.setObjectName("centralwidget")
        self.videoContainer = QtWidgets.QWidget(self.centralwidget)
        self.videoContainer.setGeometry(QtCore.QRect(-100, -40, 2100, 1300))
        self.videoContainer.setObjectName("videoContainer")
        UI_waiting.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(UI_waiting)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1800, 22))
        self.menubar.setObjectName("menubar")
        UI_waiting.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(UI_waiting)
        self.statusbar.setObjectName("statusbar")
        UI_waiting.setStatusBar(self.statusbar)

        self.retranslateUi(UI_waiting)
        QtCore.QMetaObject.connectSlotsByName(UI_waiting)

    def retranslateUi(self, UI_waiting):
        _translate = QtCore.QCoreApplication.translate
        UI_waiting.setWindowTitle(_translate("UI_waiting", "MainWindow"))
