# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ProgressBar_Bibot.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_bar(object):
    def setupUi(self, MainWindow_bar):
        MainWindow_bar.setObjectName("MainWindow_bar")
        MainWindow_bar.resize(1920, 1080)
        MainWindow_bar.setStyleSheet("background-color: rgb(23, 209, 226);")
        self.centralwidget = QtWidgets.QWidget(MainWindow_bar)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Dropshadowframe = QtWidgets.QFrame(self.centralwidget)
        self.Dropshadowframe.setStyleSheet("QFrame{\n"
"background-color: rgb(23, 209, 226);\n"
"color: rgb(230, 230, 230);\n"
"border-radius:10px;\n"
"\n"
"}\n"
"")
        self.Dropshadowframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Dropshadowframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Dropshadowframe.setObjectName("Dropshadowframe")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Dropshadowframe)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 80, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.Dropshadowframe)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(65)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.Dropshadowframe)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(25)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("\n"
"color: rgb(0, 0, 0);")
        self.label_2.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.frame = QtWidgets.QFrame(self.Dropshadowframe)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.progressBar_1 = QtWidgets.QProgressBar(self.frame)
        self.progressBar_1.setGeometry(QtCore.QRect(340, 10, 1251, 101))
        self.progressBar_1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.progressBar_1.setFont(font)
        self.progressBar_1.setStyleSheet("QProgressBar{\n"
"    \n"
"    \n"
"    background-color: rgb(230, 230, 230);\n"
"\n"
"    color: rgb(0, 0, 0);\n"
"    border-style:none;\n"
"    border-radius:30px;\n"
"    text-align:center;\n"
"}\n"
"QProgressBar::chunk{\n"
"\n"
"    border-radius:30px;\n"
"\n"
"    \n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.517045, x2:0.851, y2:0.523, stop:0 rgba(27, 200, 44, 235), stop:1 rgba(158, 255, 178, 255));\n"
"    }")
        self.progressBar_1.setProperty("value", 24)
        self.progressBar_1.setObjectName("progressBar_1")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(10, 140, 1878, 248))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(30)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("\n"
"color: rgb(0, 0, 0);")
        self.label_3.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.frame)
        self.verticalLayout.addWidget(self.Dropshadowframe)
        MainWindow_bar.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow_bar)
        self.statusbar.setObjectName("statusbar")
        MainWindow_bar.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow_bar)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_bar)

    def retranslateUi(self, MainWindow_bar):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_bar.setWindowTitle(_translate("MainWindow_bar", "MainWindow"))
        self.label.setText(_translate("MainWindow_bar", "<html><head/><body><p>Optima Robotics and Smart Robotic Center</p></body></html>"))
        self.label_2.setText(_translate("MainWindow_bar", "<html><head/><body><p><span style=\" font-weight:600;\">ASR01 </span>USER INTERFACE</p></body></html>"))
        self.label_3.setText(_translate("MainWindow_bar", "Loading..."))
