# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QT_nhapten_ID.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_nhaptenID(object):
    def setupUi(self, Form_nhaptenID):
        Form_nhaptenID.setObjectName("Form_nhaptenID")
        Form_nhaptenID.resize(750, 550)
        Form_nhaptenID.setStyleSheet("")
        self.frame = QtWidgets.QFrame(Form_nhaptenID)
        self.frame.setGeometry(QtCore.QRect(0, 0, 750, 550))
        self.frame.setMinimumSize(QtCore.QSize(750, 550))
        self.frame.setMaximumSize(QtCore.QSize(750, 550))
        self.frame.setStyleSheet("background-color: rgb(230, 230, 230);\n"
"border-radius: 35px;\n"
"box-shadow: 5px 5px 10px rgba(0, 0, 0, 0.5);")
        self.frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lineEdit_nhapID = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_nhapID.setGeometry(QtCore.QRect(110, 140, 500, 100))
        self.lineEdit_nhapID.setMinimumSize(QtCore.QSize(500, 100))
        self.lineEdit_nhapID.setMaximumSize(QtCore.QSize(500, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lineEdit_nhapID.setFont(font)
        self.lineEdit_nhapID.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:20px;")
        self.lineEdit_nhapID.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_nhapID.setObjectName("lineEdit_nhapID")
        self.Button_capnhat_name = QtWidgets.QPushButton(self.frame)
        self.Button_capnhat_name.setGeometry(QtCore.QRect(580, 470, 150, 60))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.Button_capnhat_name.setFont(font)
        self.Button_capnhat_name.setStyleSheet("QPushButton#Button_capnhat_name\n"
"{\n"
"    border-radius: 20px;\n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"    border: 1px solid rgb(230, 230, 230);\n"
"    background-color: rgb(250, 250, 250);\n"
"/*border: 3px solid rgb(0, 0, 255);*/\n"
"\n"
"}\n"
"QPushButton#Button_capnhat_name:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(58, 192, 255, 219), stop:1 rgba(58, 192, 255, 226));\n"
"\n"
"}\n"
"QPushButton#Button_capnhat_name:pressed{\n"
"padding-left :2px;\n"
"padding-top :2px;\n"
"\n"
"    background-color: rgb(58, 192, 240);\n"
"}\n"
"QPushButton#Button_capnhat_name:checked {\n"
"background-color: rgb(58, 192, 255);\n"
"\n"
"}\n"
"")
        self.Button_capnhat_name.setObjectName("Button_capnhat_name")
        self.Button_huy_capnhat_name = QtWidgets.QPushButton(self.frame)
        self.Button_huy_capnhat_name.setGeometry(QtCore.QRect(10, 470, 150, 60))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.Button_huy_capnhat_name.setFont(font)
        self.Button_huy_capnhat_name.setStyleSheet("QPushButton#Button_huy_capnhat_name\n"
"{\n"
"    border-radius: 20px;\n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"    border: 1px solid rgb(230, 230, 230);\n"
"    background-color: rgb(250, 250, 250);\n"
"/*border: 3px solid rgb(0, 0, 255);*/\n"
"\n"
"}\n"
"QPushButton#Button_huy_capnhat_name:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(58, 192, 255, 219), stop:1 rgba(58, 192, 255, 226));\n"
"\n"
"}\n"
"QPushButton#Button_huy_capnhat_name:pressed{\n"
"padding-left :2px;\n"
"padding-top :2px;\n"
"\n"
"    background-color: rgb(58, 192, 240);\n"
"}\n"
"QPushButton#Button_huy_capnhat_name:checked {\n"
"background-color: rgb(58, 192, 255);\n"
"\n"
"}\n"
"")
        self.Button_huy_capnhat_name.setObjectName("Button_huy_capnhat_name")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(110, 40, 501, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);\n"
" border-radius: 20px;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.lineEdit_nhapten = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_nhapten.setGeometry(QtCore.QRect(110, 280, 500, 100))
        self.lineEdit_nhapten.setMinimumSize(QtCore.QSize(500, 100))
        self.lineEdit_nhapten.setMaximumSize(QtCore.QSize(500, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lineEdit_nhapten.setFont(font)
        self.lineEdit_nhapten.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:20px;")
        self.lineEdit_nhapten.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_nhapten.setObjectName("lineEdit_nhapten")
        self.Button_xoa_capnhat_name = QtWidgets.QPushButton(self.frame)
        self.Button_xoa_capnhat_name.setGeometry(QtCore.QRect(200, 470, 150, 60))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.Button_xoa_capnhat_name.setFont(font)
        self.Button_xoa_capnhat_name.setStyleSheet("QPushButton#Button_xoa_capnhat_name\n"
"{\n"
"    border-radius: 20px;\n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"    border: 1px solid rgb(230, 230, 230);\n"
"    background-color: rgb(250, 250, 250);\n"
"/*border: 3px solid rgb(0, 0, 255);*/\n"
"\n"
"}\n"
"QPushButton#Button_xoa_capnhat_name:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(58, 192, 255, 219), stop:1 rgba(58, 192, 255, 226));\n"
"\n"
"}\n"
"QPushButton#Button_xoa_capnhat_name:pressed{\n"
"padding-left :2px;\n"
"padding-top :2px;\n"
"\n"
"    background-color: rgb(58, 192, 240);\n"
"}\n"
"QPushButton#Button_xoa_capnhat_name:checked {\n"
"background-color: rgb(58, 192, 255);\n"
"\n"
"}\n"
"")
        self.Button_xoa_capnhat_name.setObjectName("Button_xoa_capnhat_name")
        self.Button_xem_capnhat_name = QtWidgets.QPushButton(self.frame)
        self.Button_xem_capnhat_name.setGeometry(QtCore.QRect(380, 470, 150, 60))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.Button_xem_capnhat_name.setFont(font)
        self.Button_xem_capnhat_name.setStyleSheet("QPushButton#Button_xem_capnhat_name\n"
"{\n"
"    border-radius: 20px;\n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"    border: 1px solid rgb(230, 230, 230);\n"
"    background-color: rgb(250, 250, 250);\n"
"/*border: 3px solid rgb(0, 0, 255);*/\n"
"\n"
"}\n"
"QPushButton#Button_xem_capnhat_name:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(58, 192, 255, 219), stop:1 rgba(58, 192, 255, 226));\n"
"\n"
"}\n"
"QPushButton#Button_xem_capnhat_name:pressed{\n"
"padding-left :2px;\n"
"padding-top :2px;\n"
"\n"
"    background-color: rgb(58, 192, 240);\n"
"}\n"
"QPushButton#Button_xem_capnhat_name:checked {\n"
"background-color: rgb(58, 192, 255);\n"
"\n"
"}\n"
"")
        self.Button_xem_capnhat_name.setObjectName("Button_xem_capnhat_name")

        self.retranslateUi(Form_nhaptenID)
        QtCore.QMetaObject.connectSlotsByName(Form_nhaptenID)

    def retranslateUi(self, Form_nhaptenID):
        _translate = QtCore.QCoreApplication.translate
        Form_nhaptenID.setWindowTitle(_translate("Form_nhaptenID", "Form"))
        self.lineEdit_nhapID.setPlaceholderText(_translate("Form_nhaptenID", "   Nhập ID"))
        self.Button_capnhat_name.setText(_translate("Form_nhaptenID", "CẬP NHẬT"))
        self.Button_huy_capnhat_name.setText(_translate("Form_nhaptenID", "HỦY"))
        self.label.setText(_translate("Form_nhaptenID", "Vui lòng nhập ID và Name"))
        self.lineEdit_nhapten.setPlaceholderText(_translate("Form_nhaptenID", "   Nhập Name"))
        self.Button_xoa_capnhat_name.setText(_translate("Form_nhaptenID", "XÓA"))
        self.Button_xem_capnhat_name.setText(_translate("Form_nhaptenID", "XEM"))
