# -*- coding: utf-8 -*-

"""
File: virtualKbd.py
Description: This file demonstrates an example Python script.
Author: Nader Hany
"""
from PyQt5.QtGui import QMouseEvent
from PyQt5.QtCore import (

    QCoreApplication,
    QDate,
    QDateTime,
    QLocale,
    QMetaObject,
    QObject,
    QPoint,
    QRect,
    QSize,
    QTime,
    QUrl,
    Qt,
    QTimer,
)
from PyQt5.QtGui import (
    QBrush,
    QColor,
    QConicalGradient,
    QCursor,
    QFont,
    QFontDatabase,
    QGradient,
    QIcon,
    QImage,
    QKeySequence,
    QLinearGradient,
    QPainter,
    QPalette,
    QPixmap,
    QRadialGradient,
    QTransform
)
from PyQt5.QtWidgets import (
    QApplication,
    QDialog,
    QLabel,
    QPushButton,
    QSizePolicy,
    QWidget,
    QLineEdit
)
from PyQt5.QtGui import QKeyEvent
from functools import partial


#########################################################
# will start the virtual ketboard in only one inistance
#########################################################
class Registe():
    def __init__(self, QLnEdt):
        #QLnEdt : should be a QLineEadit object
        self.mylnedt = QLnEdt
        #QLnEdt.mousePressEvent = self.show2
        #self.show2()
    def show2(self, event=None):
        try:
            if not hasattr(Registe, "virtual_keyboard") or not Registe.virtual_keyboard.isVisible():
                Registe.virtual_keyboard = VKBD(self.mylnedt)
                Registe.virtual_keyboard.show()
            else:
                Registe.virtual_keyboard.activateWindow()
        except:
            print("failed to open virtual keyboard ,already exist ")


class VKBD(QDialog):
    def __init__(self, linedt):
        super().__init__()
        self.setupUi(self)
        self.switch = "letters"
        self.shiftCTR = 0
        self.LNEDT = linedt
        self.output = linedt.text()
        self.label.setText(linedt.text())

        # Timer for Long Press

        self.long_press_timer = QTimer()
        self.long_press_timer.timeout.connect(self.long_press_timeout)


    # Auto Generated By qt designer

    def setupUi(self, Dialog):
        Dialog.setFixedSize(1920, 450)
        #Dialog.setFixedSize(710, 240)
        Dialog.setGeometry(0, 630, 1920, 450)
        #Dialog.setGeometry(610, 650, 710, 240)
        self.setWindowFlag(Qt.FramelessWindowHint)
        Dialog.setStyleSheet("background-color: rgb(255,255 ,255);")  # màu nền keyboard
        self.pushButton_5 = QPushButton(Dialog)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_5.setGeometry(QRect(40, 250, 243, 84))  # size của nút shift (20, 140,243, 84)
        font = QFont()
        font.setPointSize(30)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet(  # nút shift
            "background-color: rgb(240, 240, 240);\n"
            "color: rgb(0, 0, 0);\n"
            "border-radius: 10px;"
        )
        self.pushButton_3 = QPushButton(Dialog)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.setGeometry(QRect(30, 50, 157, 84)) # 58 => 157, 45 => 84
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet(
            "background-color: rgb(240, 240, 240);\n"
            "color: rgb(0, 0, 0);\n"
            "border-radius: 10px;"
        )
        self.pushButton_4 = QPushButton(Dialog)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.setGeometry(QRect(220, 50, 157, 84))
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet(
            "background-color: rgb(240, 240, 240);\n"
            "color: rgb(0, 0, 0);\n"
            "border-radius: 10px;"
        )
        self.pushButton_6 = QPushButton(Dialog)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_6.setGeometry(QRect(410, 50, 157, 84))
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet(
            "background-color: rgb(240, 240, 240);\n"
            "color: rgb(0, 0, 0);\n"
            "border-radius: 10px;"
        )
        self.pushButton_19 = QPushButton(Dialog)
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_19.setGeometry(QRect(600, 50, 157, 84))
        self.pushButton_19.setFont(font)
        self.pushButton_19.setStyleSheet(
            "background-color: rgb(240, 240, 240);\n"
            "color: rgb(0, 0, 0);\n"
            "border-radius: 10px;"
        )
        self.pushButton_20 = QPushButton(Dialog)
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_20.setGeometry(QRect(790, 50, 157, 84))
        self.pushButton_20.setFont(font)
        self.pushButton_20.setStyleSheet(
            "background-color: rgb(240, 240, 240);\n"
            "color: rgb(0, 0, 0);\n"
            "border-radius: 10px;"
        )
        self.pushButton_21 = QPushButton(Dialog)
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_21.setGeometry(QRect(980, 50, 157, 84))
        self.pushButton_21.setFont(font)
        self.pushButton_21.setStyleSheet(
            "background-color: rgb(240, 240, 240);\n"
            "color: rgb(0, 0, 0);\n"
            "border-radius: 10px;"
        )
        self.pushButton_22 = QPushButton(Dialog)
        self.pushButton_22.setObjectName("pushButton_22")
        self.pushButton_22.setGeometry(QRect(1170, 50, 157, 84))
        self.pushButton_22.setFont(font)
        self.pushButton_22.setStyleSheet(
            "background-color: rgb(240, 240, 240);\n"
            "color: rgb(0, 0, 0);\n"
            "border-radius: 10px;"
        )
        self.pushButton_23 = QPushButton(Dialog)
        self.pushButton_23.setObjectName("pushButton_23")
        self.pushButton_23.setGeometry(QRect(1360, 50, 157, 84))
        self.pushButton_23.setFont(font)
        self.pushButton_23.setStyleSheet(
            "background-color: rgb(240, 240, 240);\n"
            "color: rgb(0, 0, 0);\n"
            "border-radius: 10px;"
        )
        self.pushButton_24 = QPushButton(Dialog)
        self.pushButton_24.setObjectName("pushButton_24")
        self.pushButton_24.setGeometry(QRect(1550, 50, 157, 84))
        self.pushButton_24.setFont(font)
        self.pushButton_24.setStyleSheet(
            "background-color: rgb(240, 240, 240);\n"
            "color: rgb(0, 0, 0);\n"
            "border-radius: 10px;"
        )
        self.pushButton_26 = QPushButton(Dialog)
        self.pushButton_26.setObjectName("pushButton_26")
        self.pushButton_26.setGeometry(QRect(1646, 250, 243, 84))
        self.pushButton_26.setFont(font)
        self.pushButton_26.setStyleSheet(
            "background-color: rgb(240, 240, 240);\n"
            "color: rgb(0, 0, 0);\n"
            "border-radius: 10px;"
        )
        self.pushButton_27 = QPushButton(Dialog)
        self.pushButton_27.setObjectName("pushButton_27")
        self.pushButton_27.setGeometry(QRect(1740, 50, 157, 84))
        self.pushButton_27.setFont(font)
        self.pushButton_27.setStyleSheet(
            "background-color: rgb(240, 240, 240);\n"
            "color: rgb(0, 0, 0);\n"
            "border-radius: 10px;"
        )
        self.pushButton_28 = QPushButton(Dialog)
        self.pushButton_28.setObjectName("pushButton_28")
        self.pushButton_28.setGeometry(QRect(1600, 350, 291, 84))
        self.pushButton_28.setFont(font)
        self.pushButton_28.setStyleSheet(
            "background-color: rgb(240, 240, 240);\n"
            "color: rgb(0, 0, 0);\n"
            "border-radius: 10px;"
        )
        self.pushButton_25 = QPushButton(Dialog)
        self.pushButton_25.setObjectName("pushButton_25")
        self.pushButton_25.setGeometry(QRect(1630, 150, 157, 84))
        self.pushButton_25.setFont(font)
        self.pushButton_25.setStyleSheet(
            "background-color: rgb(240, 240, 240);\n"
            "color: rgb(0, 0, 0);\n"
            "border-radius: 10px;"
        )
        self.pushButton_29 = QPushButton(Dialog)
        self.pushButton_29.setObjectName("pushButton_29")
        self.pushButton_29.setGeometry(QRect(1440, 150, 157, 84))
        self.pushButton_29.setFont(font)
        self.pushButton_29.setStyleSheet(
            "background-color: rgb(240, 240, 240);\n"
            "color: rgb(0, 0, 0);\n"
            "border-radius: 10px;"
        )
        self.pushButton_30 = QPushButton(Dialog)
        self.pushButton_30.setObjectName("pushButton_30")
        self.pushButton_30.setGeometry(QRect(300, 150, 157, 84))
        self.pushButton_30.setFont(font)
        self.pushButton_30.setStyleSheet(
            "background-color: rgb(240, 240, 240);\n"
            "color: rgb(0, 0, 0);\n"
            "border-radius: 10px;"
        )
        self.pushButton_31 = QPushButton(Dialog)
        self.pushButton_31.setObjectName("pushButton_31")
        self.pushButton_31.setGeometry(QRect(1060, 150, 157, 84))
        self.pushButton_31.setFont(font)
        self.pushButton_31.setStyleSheet(
            "background-color: rgb(240, 240, 240);\n"
            "color: rgb(0, 0, 0);\n"
            "border-radius: 10px;"
        )
        self.pushButton_32 = QPushButton(Dialog)
        self.pushButton_32.setObjectName("pushButton_32")
        self.pushButton_32.setGeometry(QRect(680, 150, 157, 84))
        self.pushButton_32.setFont(font)
        self.pushButton_32.setStyleSheet(
            "background-color: rgb(240, 240, 240);\n"
            "color: rgb(0, 0, 0);\n"
            "border-radius: 10px;"
        )
        self.pushButton_33 = QPushButton(Dialog)
        self.pushButton_33.setObjectName("pushButton_33")
        self.pushButton_33.setGeometry(QRect(1250, 150, 157, 84))
        self.pushButton_33.setFont(font)
        self.pushButton_33.setStyleSheet(
            "background-color: rgb(240, 240, 240);\n"
            "color: rgb(0, 0, 0);\n"
            "border-radius: 10px;"
        )
        self.pushButton_34 = QPushButton(Dialog)
        self.pushButton_34.setObjectName("pushButton_34")
        self.pushButton_34.setGeometry(QRect(490, 150, 157, 84))
        self.pushButton_34.setFont(font)
        self.pushButton_34.setStyleSheet(
            "background-color: rgb(240, 240, 240);\n"
            "color: rgb(0, 0, 0);\n"
            "border-radius: 10px;"
        )
        self.pushButton_35 = QPushButton(Dialog) # nút chữ a
        self.pushButton_35.setObjectName("pushButton_35")
        self.pushButton_35.setGeometry(QRect(110, 150, 157, 84))
        self.pushButton_35.setFont(font)
        self.pushButton_35.setStyleSheet(
            "background-color: rgb(240, 240, 240);\n"
            "color: rgb(0, 0, 0);\n"
            "border-radius: 10px;"
        )
        self.pushButton_36 = QPushButton(Dialog)
        self.pushButton_36.setObjectName("pushButton_36")
        self.pushButton_36.setGeometry(QRect(870, 150, 157, 84))
        self.pushButton_36.setFont(font)
        self.pushButton_36.setStyleSheet(
            "background-color: rgb(240, 240, 240);\n"
            "color: rgb(0, 0, 0);\n"
            "border-radius: 10px;"
        )
        self.pushButton_37 = QPushButton(Dialog)
        self.pushButton_37.setObjectName("pushButton_37")
        self.pushButton_37.setGeometry(QRect(506, 250, 157, 84))
        self.pushButton_37.setFont(font)
        self.pushButton_37.setStyleSheet(
            "background-color: rgb(240, 240, 240);\n"
            "color: rgb(0, 0, 0);\n"
            "border-radius: 10px;"
        )
        self.pushButton_38 = QPushButton(Dialog)
        self.pushButton_38.setObjectName("pushButton_38")
        self.pushButton_38.setGeometry(QRect(886, 250, 157, 84))
        self.pushButton_38.setFont(font)
        self.pushButton_38.setStyleSheet(
            "background-color: rgb(240, 240, 240);\n"
            "color: rgb(0, 0, 0);\n"
            "border-radius: 10px;"
        )
        self.pushButton_39 = QPushButton(Dialog)
        self.pushButton_39.setObjectName("pushButton_39")
        self.pushButton_39.setGeometry(QRect(1456, 250, 157, 84))
        self.pushButton_39.setFont(font)
        self.pushButton_39.setStyleSheet(
            "background-color: rgb(240, 240, 240);\n"
            "color: rgb(0, 0, 0);\n"
            "border-radius: 10px;"
        )
        self.pushButton_40 = QPushButton(Dialog)
        self.pushButton_40.setObjectName("pushButton_40")
        self.pushButton_40.setGeometry(QRect(696, 250, 157, 84))
        self.pushButton_40.setFont(font)
        self.pushButton_40.setStyleSheet(
            "background-color: rgb(240, 240, 240);\n"
            "color: rgb(0, 0, 0);\n"
            "border-radius: 10px;"
        )
        self.pushButton_41 = QPushButton(Dialog)
        self.pushButton_41.setObjectName("pushButton_41")
        self.pushButton_41.setGeometry(QRect(306, 350, 117, 84))
        self.pushButton_41.setFont(font)
        self.pushButton_41.setStyleSheet(
            "background-color: rgb(240, 240, 240);\n"
            "color: rgb(0, 0, 0);\n"
            "border-radius: 10px;"
        )
        self.pushButton_42 = QPushButton(Dialog)
        self.pushButton_42.setObjectName("pushButton_42")
        self.pushButton_42.setGeometry(QRect(1452, 350, 117, 84))
        self.pushButton_42.setFont(font)
        self.pushButton_42.setStyleSheet(
            "background-color: rgb(240, 240, 240);\n"
            "color: rgb(0, 0, 0);\n"
            "border-radius: 10px;"
        )
        self.pushButton_43 = QPushButton(Dialog)
        self.pushButton_43.setObjectName("pushButton_43")
        self.pushButton_43.setGeometry(QRect(316, 250, 157, 84))
        self.pushButton_43.setFont(font)
        self.pushButton_43.setStyleSheet(
            "background-color: rgb(240, 240, 240);\n"
            "color: rgb(0, 0, 0);\n"
            "border-radius: 10px;"
        )
        self.pushButton_44 = QPushButton(Dialog)
        self.pushButton_44.setObjectName("pushButton_44")
        self.pushButton_44.setGeometry(QRect(1076, 250, 157, 84))
        self.pushButton_44.setFont(font)
        self.pushButton_44.setStyleSheet(
            "background-color: rgb(240, 240, 240);\n"
            "color: rgb(0, 0, 0);\n"
            "border-radius: 10px;"
        )
        self.pushButton_45 = QPushButton(Dialog)
        self.pushButton_45.setObjectName("pushButton_45")
        self.pushButton_45.setGeometry(QRect(1266, 250, 157, 84))
        self.pushButton_45.setFont(font)
        self.pushButton_45.setStyleSheet(
            "background-color: rgb(240, 240, 240);\n"
            "color: rgb(0, 0, 0);\n"
            "border-radius: 10px;"
        )
        self.pushButton_46 = QPushButton(Dialog)
        self.pushButton_46.setObjectName("pushButton_46")
        self.pushButton_46.setGeometry(QRect(456, 350,960, 84))
        self.pushButton_46.setFont(font)
        self.pushButton_46.setStyleSheet(
            "background-color: rgb(240, 240, 240);\n"
            "color: rgb(0, 0, 0);\n"
            "border-radius: 10px;"
        )
        self.pushButton_7 = QPushButton(Dialog)
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_7.setGeometry(QRect(30, 350, 243, 84))
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet(
            "background-color: rgb(240, 240, 240);\n"
            "color: rgb(0, 0, 0);\n"
            "border-radius: 10px;"
        )
        self.label = QLabel(Dialog)  # ==============Phần ký tự hiện lên text khi nhập
        self.label.setObjectName("label")
        self.label.setGeometry(QRect(20, 2, 401, 35))
        self.label.setFont(font)
        self.label.setStyleSheet(
            "background-color: rgb(255, 255, 255);\n" "color: rgb(255, 255, 255);"
        )

        self.retranslateUi(Dialog)

        QMetaObject.connectSlotsByName(Dialog)

    # setupUi

    # Auto generated by qt designer
    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(
            QCoreApplication.translate("Dialog", " ", None)

        )
        self.pushButton_5.setText(QCoreApplication.translate("Dialog", "Shift", None))
        self.pushButton_3.setText(QCoreApplication.translate("Dialog", "q", None))
        self.pushButton_4.setText(QCoreApplication.translate("Dialog", "w", None))
        self.pushButton_6.setText(QCoreApplication.translate("Dialog", "e", None))
        self.pushButton_19.setText(QCoreApplication.translate("Dialog", "r", None))
        self.pushButton_20.setText(QCoreApplication.translate("Dialog", "t", None))
        self.pushButton_21.setText(QCoreApplication.translate("Dialog", "y", None))
        self.pushButton_22.setText(QCoreApplication.translate("Dialog", "u", None))
        self.pushButton_23.setText(QCoreApplication.translate("Dialog", "i", None))
        self.pushButton_24.setText(QCoreApplication.translate("Dialog", "o", None))
        self.pushButton_26.setText(QCoreApplication.translate("Dialog", "clear", None))
        self.pushButton_27.setText(QCoreApplication.translate("Dialog", "p", None))
        self.pushButton_28.setText(QCoreApplication.translate("Dialog", "Enter", None))
        self.pushButton_25.setText(QCoreApplication.translate("Dialog", "l", None))
        self.pushButton_29.setText(QCoreApplication.translate("Dialog", "k", None))
        self.pushButton_30.setText(QCoreApplication.translate("Dialog", "s", None))
        self.pushButton_31.setText(QCoreApplication.translate("Dialog", "h", None))
        self.pushButton_32.setText(QCoreApplication.translate("Dialog", "f", None))
        self.pushButton_33.setText(QCoreApplication.translate("Dialog", "j", None))
        self.pushButton_34.setText(QCoreApplication.translate("Dialog", "d", None))
        self.pushButton_35.setText(QCoreApplication.translate("Dialog", "a", None))
        self.pushButton_36.setText(QCoreApplication.translate("Dialog", "g", None))
        self.pushButton_37.setText(QCoreApplication.translate("Dialog", "x", None))
        self.pushButton_38.setText(QCoreApplication.translate("Dialog", "v", None))
        self.pushButton_39.setText(QCoreApplication.translate("Dialog", "m", None))
        self.pushButton_40.setText(QCoreApplication.translate("Dialog", "c", None))
        self.pushButton_41.setText(QCoreApplication.translate("Dialog", ",", None))
        self.pushButton_42.setText(QCoreApplication.translate("Dialog", ".", None))
        self.pushButton_43.setText(QCoreApplication.translate("Dialog", "z", None))
        self.pushButton_44.setText(QCoreApplication.translate("Dialog", "b", None))
        self.pushButton_45.setText(QCoreApplication.translate("Dialog", "n", None))
        self.pushButton_46.setText(" ")
        self.pushButton_7.setText(QCoreApplication.translate("Dialog", "123", None))

        # Enter Button clicked callback
        self.pushButton_28.clicked.connect(self.enter_callBack)

        # 123/abc Button clicked callback
        self.pushButton_7.clicked.connect(self.show123abc)

        # Shift Key clicked callback
        self.pushButton_5.clicked.connect(self.shiftCliked)

        self.label.setText(QCoreApplication.translate("Dialog", "", None))

        buttons = [
            button
            for button in self.findChildren(QPushButton)
            if button.objectName().startswith("pushButton")
        ]

        # Connect pressed and released signals of each button
        for button in buttons:
            button.pressed.connect(partial(self.button_pressed, button))
            button.released.connect(partial(self.button_released, button))

    # retranslateUi

    # this will emmit when clicking enter button
    def enter_callBack(self):
        self.accept()  # đóng hộp thoại Diaglog

    # on every time you press 123 button it will switch the buttons from letters to numbers and vice versea
    def show123abc(self):
        if self.switch == "letters":
            self.switch = "123"
            self.pushButton_5.setText(
                QCoreApplication.translate("Dialog", "Shift", None)
            )
            self.pushButton_3.setText(QCoreApplication.translate("Dialog", "1", None))
            self.pushButton_4.setText(QCoreApplication.translate("Dialog", "2", None))
            self.pushButton_6.setText(QCoreApplication.translate("Dialog", "3", None))
            self.pushButton_19.setText(QCoreApplication.translate("Dialog", "4", None))
            self.pushButton_20.setText(QCoreApplication.translate("Dialog", "5", None))
            self.pushButton_21.setText(QCoreApplication.translate("Dialog", "6", None))
            self.pushButton_22.setText(QCoreApplication.translate("Dialog", "7", None))
            self.pushButton_23.setText(QCoreApplication.translate("Dialog", "8", None))
            self.pushButton_24.setText(QCoreApplication.translate("Dialog", "9", None))
            self.pushButton_26.setText(QCoreApplication.translate("Dialog", "clear", None))
            self.pushButton_27.setText(QCoreApplication.translate("Dialog", "0", None))
            self.pushButton_28.setText(
                QCoreApplication.translate("Dialog", "Enter", None)
            )
            self.pushButton_25.setText(QCoreApplication.translate("Dialog", "=", None))
            self.pushButton_29.setText(QCoreApplication.translate("Dialog", ")", None))
            self.pushButton_30.setText(QCoreApplication.translate("Dialog", "#", None))
            self.pushButton_31.setText(QCoreApplication.translate("Dialog", "-", None))
            self.pushButton_32.setText(QCoreApplication.translate("Dialog", "&&", None))
            self.pushButton_33.setText(QCoreApplication.translate("Dialog", "(", None))
            self.pushButton_34.setText(QCoreApplication.translate("Dialog", "$", None))
            self.pushButton_35.setText(QCoreApplication.translate("Dialog", "@", None))
            self.pushButton_36.setText(QCoreApplication.translate("Dialog", "_", None))
            self.pushButton_37.setText(QCoreApplication.translate("Dialog", "*", None))
            self.pushButton_38.setText(QCoreApplication.translate("Dialog", ":", None))
            self.pushButton_39.setText(QCoreApplication.translate("Dialog", "?", None))
            self.pushButton_40.setText(QCoreApplication.translate("Dialog", "'", None))
            self.pushButton_41.setText(QCoreApplication.translate("Dialog", "+", None))
            self.pushButton_42.setText(QCoreApplication.translate("Dialog", ".", None))
            self.pushButton_43.setText(QCoreApplication.translate("Dialog", '"', None))
            self.pushButton_44.setText(QCoreApplication.translate("Dialog", "/", None))
            self.pushButton_45.setText(QCoreApplication.translate("Dialog", "!", None))
            self.pushButton_46.setText(" ")
            self.pushButton_7.setText(QCoreApplication.translate("Dialog", "abc", None))
        else:
            self.switch = "letters"
            self.pushButton_5.setText(
                QCoreApplication.translate("Dialog", "Shift", None)
            )
            self.pushButton_3.setText(QCoreApplication.translate("Dialog", "q", None))
            self.pushButton_4.setText(QCoreApplication.translate("Dialog", "w", None))
            self.pushButton_6.setText(QCoreApplication.translate("Dialog", "e", None))
            self.pushButton_19.setText(QCoreApplication.translate("Dialog", "r", None))
            self.pushButton_20.setText(QCoreApplication.translate("Dialog", "t", None))
            self.pushButton_21.setText(QCoreApplication.translate("Dialog", "y", None))
            self.pushButton_22.setText(QCoreApplication.translate("Dialog", "u", None))
            self.pushButton_23.setText(QCoreApplication.translate("Dialog", "i", None))
            self.pushButton_24.setText(QCoreApplication.translate("Dialog", "o", None))
            self.pushButton_26.setText(QCoreApplication.translate("Dialog", "clear", None))
            self.pushButton_27.setText(QCoreApplication.translate("Dialog", "p", None))
            self.pushButton_28.setText(
                QCoreApplication.translate("Dialog", "Enter", None)
            )
            self.pushButton_25.setText(QCoreApplication.translate("Dialog", "l", None))
            self.pushButton_29.setText(QCoreApplication.translate("Dialog", "k", None))
            self.pushButton_30.setText(QCoreApplication.translate("Dialog", "s", None))
            self.pushButton_31.setText(QCoreApplication.translate("Dialog", "h", None))
            self.pushButton_32.setText(QCoreApplication.translate("Dialog", "f", None))
            self.pushButton_33.setText(QCoreApplication.translate("Dialog", "j", None))
            self.pushButton_34.setText(QCoreApplication.translate("Dialog", "d", None))
            self.pushButton_35.setText(QCoreApplication.translate("Dialog", "a", None))
            self.pushButton_36.setText(QCoreApplication.translate("Dialog", "g", None))
            self.pushButton_37.setText(QCoreApplication.translate("Dialog", "x", None))
            self.pushButton_38.setText(QCoreApplication.translate("Dialog", "v", None))
            self.pushButton_39.setText(QCoreApplication.translate("Dialog", "m", None))
            self.pushButton_40.setText(QCoreApplication.translate("Dialog", "c", None))
            self.pushButton_41.setText(QCoreApplication.translate("Dialog", ",", None))
            self.pushButton_42.setText(QCoreApplication.translate("Dialog", ".", None))
            self.pushButton_43.setText(QCoreApplication.translate("Dialog", "z", None))
            self.pushButton_44.setText(QCoreApplication.translate("Dialog", "b", None))
            self.pushButton_45.setText(QCoreApplication.translate("Dialog", "n", None))
            self.pushButton_46.setText(" ")
            self.pushButton_7.setText(QCoreApplication.translate("Dialog", "123", None))
            # self.pushButton_19.text()

    # this will emmit when clicking shift button
    def shiftCliked(self):
        self.shiftCTR += 1
        if self.switch == "letters":
            self.pushButton_5.setText(
                QCoreApplication.translate("Dialog", "Shift", None)
            )
            self.pushButton_3.setText(QCoreApplication.translate("Dialog", "Q", None))
            self.pushButton_4.setText(QCoreApplication.translate("Dialog", "W", None))
            self.pushButton_6.setText(QCoreApplication.translate("Dialog", "E", None))
            self.pushButton_19.setText(QCoreApplication.translate("Dialog", "R", None))
            self.pushButton_20.setText(QCoreApplication.translate("Dialog", "T", None))
            self.pushButton_21.setText(QCoreApplication.translate("Dialog", "Y", None))
            self.pushButton_22.setText(QCoreApplication.translate("Dialog", "U", None))
            self.pushButton_23.setText(QCoreApplication.translate("Dialog", "I", None))
            self.pushButton_24.setText(QCoreApplication.translate("Dialog", "O", None))
            self.pushButton_26.setText(QCoreApplication.translate("Dialog", "clear", None))
            self.pushButton_27.setText(QCoreApplication.translate("Dialog", "P", None))
            self.pushButton_28.setText(
                QCoreApplication.translate("Dialog", "Enter", None)
            )
            self.pushButton_25.setText(QCoreApplication.translate("Dialog", "L", None))
            self.pushButton_29.setText(QCoreApplication.translate("Dialog", "K", None))
            self.pushButton_30.setText(QCoreApplication.translate("Dialog", "S", None))
            self.pushButton_31.setText(QCoreApplication.translate("Dialog", "H", None))
            self.pushButton_32.setText(QCoreApplication.translate("Dialog", "F", None))
            self.pushButton_33.setText(QCoreApplication.translate("Dialog", "J", None))
            self.pushButton_34.setText(QCoreApplication.translate("Dialog", "D", None))
            self.pushButton_35.setText(QCoreApplication.translate("Dialog", "A", None))
            self.pushButton_36.setText(QCoreApplication.translate("Dialog", "G", None))
            self.pushButton_37.setText(QCoreApplication.translate("Dialog", "X", None))
            self.pushButton_38.setText(QCoreApplication.translate("Dialog", "V", None))
            self.pushButton_39.setText(QCoreApplication.translate("Dialog", "M", None))
            self.pushButton_40.setText(QCoreApplication.translate("Dialog", "C", None))
            self.pushButton_41.setText(QCoreApplication.translate("Dialog", ",", None))
            self.pushButton_42.setText(QCoreApplication.translate("Dialog", ".", None))
            self.pushButton_43.setText(QCoreApplication.translate("Dialog", "Z", None))
            self.pushButton_44.setText(QCoreApplication.translate("Dialog", "B", None))
            self.pushButton_45.setText(QCoreApplication.translate("Dialog", "N", None))
        if self.switch == "letters" and self.shiftCTR > 2:
            self.shiftCTR = 0
            self.pushButton_5.setText(
                QCoreApplication.translate("Dialog", "Shift", None)
            )
            self.pushButton_3.setText(QCoreApplication.translate("Dialog", "q", None))
            self.pushButton_4.setText(QCoreApplication.translate("Dialog", "w", None))
            self.pushButton_6.setText(QCoreApplication.translate("Dialog", "e", None))
            self.pushButton_19.setText(QCoreApplication.translate("Dialog", "r", None))
            self.pushButton_20.setText(QCoreApplication.translate("Dialog", "t", None))
            self.pushButton_21.setText(QCoreApplication.translate("Dialog", "y", None))
            self.pushButton_22.setText(QCoreApplication.translate("Dialog", "u", None))
            self.pushButton_23.setText(QCoreApplication.translate("Dialog", "i", None))
            self.pushButton_24.setText(QCoreApplication.translate("Dialog", "o", None))
            self.pushButton_26.setText(QCoreApplication.translate("Dialog", "clear", None))
            self.pushButton_27.setText(QCoreApplication.translate("Dialog", "p", None))
            self.pushButton_28.setText(
                QCoreApplication.translate("Dialog", "Enter", None)
            )
            self.pushButton_25.setText(QCoreApplication.translate("Dialog", "l", None))
            self.pushButton_29.setText(QCoreApplication.translate("Dialog", "k", None))
            self.pushButton_30.setText(QCoreApplication.translate("Dialog", "s", None))
            self.pushButton_31.setText(QCoreApplication.translate("Dialog", "h", None))
            self.pushButton_32.setText(QCoreApplication.translate("Dialog", "f", None))
            self.pushButton_33.setText(QCoreApplication.translate("Dialog", "j", None))
            self.pushButton_34.setText(QCoreApplication.translate("Dialog", "d", None))
            self.pushButton_35.setText(QCoreApplication.translate("Dialog", "a", None))
            self.pushButton_36.setText(QCoreApplication.translate("Dialog", "g", None))
            self.pushButton_37.setText(QCoreApplication.translate("Dialog", "x", None))
            self.pushButton_38.setText(QCoreApplication.translate("Dialog", "v", None))
            self.pushButton_39.setText(QCoreApplication.translate("Dialog", "m", None))
            self.pushButton_40.setText(QCoreApplication.translate("Dialog", "c", None))
            self.pushButton_41.setText(QCoreApplication.translate("Dialog", ",", None))
            self.pushButton_42.setText(QCoreApplication.translate("Dialog", ".", None))
            self.pushButton_43.setText(QCoreApplication.translate("Dialog", "z", None))
            self.pushButton_44.setText(QCoreApplication.translate("Dialog", "b", None))
            self.pushButton_45.setText(QCoreApplication.translate("Dialog", "n", None))
            self.pushButton_46.setText(" ")

            self.pushButton_5.setStyleSheet(
                "background-color: rgb(240, 240, 240);\n"
                "color: rgb(0, 0, 0);\n"
                "border-radius: 10px;"
            )

    # press callback for every button #=========================Khi nhấn sẽ đổi màu nút===========#
    def button_pressed(self, button):
        button.setStyleSheet(
            "background-color: rgb(190, 190, 190);\n"
            "color: rgb(0, 0, 0);\n"
            "border-radius: 10px;"
        )
        if button.text() != "Shift" and button.text() != "clear" and button.text() != "123" and button.text() != "abc" and button.text() != "&&" and button.text() != "Enter":
            self.label.setText(self.label.text() + button.text())
            self.output = self.label.text()
        if button.text() == "clear":
            self.label.setText(self.label.text()[:-1])
            self.output = self.label.text()
            self.long_press_timer.start(1000)  # Set the timer interval (in milliseconds) for long press detection

        if button.text() == "&&":
            self.label.setText(self.label.text() + "&")
            self.output = self.label.text()

        self.LNEDT.setText(self.output)

        # relese callback for every button release

    def button_released(self, button):  # ======================= xác nhận giữ nút==========#
        button.setStyleSheet(
            "background-color: rgb(240, 240, 240);\n"
            "color: rgb(0, 0, 0);\n"
            "border-radius: 10px;"
        )

        if button.text() == "clear":
            self.long_press_timer.stop()

        if (
                self.shiftCTR > 0
                and self.shiftCTR < 2
                and self.switch == "letters"
                and button.text() != "Shift"
        ):
            self.pushButton_5.setText(
                QCoreApplication.translate("Dialog", "Shift", None)
            )
            self.pushButton_3.setText(QCoreApplication.translate("Dialog", "q", None))
            self.pushButton_4.setText(QCoreApplication.translate("Dialog", "w", None))
            self.pushButton_6.setText(QCoreApplication.translate("Dialog", "e", None))
            self.pushButton_19.setText(QCoreApplication.translate("Dialog", "r", None))
            self.pushButton_20.setText(QCoreApplication.translate("Dialog", "t", None))
            self.pushButton_21.setText(QCoreApplication.translate("Dialog", "y", None))
            self.pushButton_22.setText(QCoreApplication.translate("Dialog", "u", None))
            self.pushButton_23.setText(QCoreApplication.translate("Dialog", "i", None))
            self.pushButton_24.setText(QCoreApplication.translate("Dialog", "o", None))
            self.pushButton_26.setText(QCoreApplication.translate("Dialog", "clear", None))
            self.pushButton_27.setText(QCoreApplication.translate("Dialog", "p", None))
            self.pushButton_28.setText(
                QCoreApplication.translate("Dialog", "Enter", None)
            )
            self.pushButton_25.setText(QCoreApplication.translate("Dialog", "l", None))
            self.pushButton_29.setText(QCoreApplication.translate("Dialog", "k", None))
            self.pushButton_30.setText(QCoreApplication.translate("Dialog", "s", None))
            self.pushButton_31.setText(QCoreApplication.translate("Dialog", "h", None))
            self.pushButton_32.setText(QCoreApplication.translate("Dialog", "f", None))
            self.pushButton_33.setText(QCoreApplication.translate("Dialog", "j", None))
            self.pushButton_34.setText(QCoreApplication.translate("Dialog", "d", None))
            self.pushButton_35.setText(QCoreApplication.translate("Dialog", "a", None))
            self.pushButton_36.setText(QCoreApplication.translate("Dialog", "g", None))
            self.pushButton_37.setText(QCoreApplication.translate("Dialog", "x", None))
            self.pushButton_38.setText(QCoreApplication.translate("Dialog", "v", None))
            self.pushButton_39.setText(QCoreApplication.translate("Dialog", "m", None))
            self.pushButton_40.setText(QCoreApplication.translate("Dialog", "c", None))
            self.pushButton_41.setText(QCoreApplication.translate("Dialog", ",", None))
            self.pushButton_42.setText(QCoreApplication.translate("Dialog", ".", None))
            self.pushButton_43.setText(QCoreApplication.translate("Dialog", "z", None))
            self.pushButton_44.setText(QCoreApplication.translate("Dialog", "b", None))
            self.pushButton_45.setText(QCoreApplication.translate("Dialog", "n", None))
            self.pushButton_46.setText(" ")
            self.pushButton_7.setText(QCoreApplication.translate("Dialog", "123", None))
            self.shiftCTR = 0

        if self.shiftCTR > 0 and self.shiftCTR < 3 and self.switch == "letters":
            self.pushButton_5.setText(
                QCoreApplication.translate("Dialog", "Shift", None)
            )
            self.pushButton_3.setText(QCoreApplication.translate("Dialog", "Q", None))
            self.pushButton_4.setText(QCoreApplication.translate("Dialog", "W", None))
            self.pushButton_6.setText(QCoreApplication.translate("Dialog", "E", None))
            self.pushButton_19.setText(QCoreApplication.translate("Dialog", "R", None))
            self.pushButton_20.setText(QCoreApplication.translate("Dialog", "T", None))
            self.pushButton_21.setText(QCoreApplication.translate("Dialog", "Y", None))
            self.pushButton_22.setText(QCoreApplication.translate("Dialog", "U", None))
            self.pushButton_23.setText(QCoreApplication.translate("Dialog", "I", None))
            self.pushButton_24.setText(QCoreApplication.translate("Dialog", "O", None))
            self.pushButton_26.setText(QCoreApplication.translate("Dialog", "clear", None))
            self.pushButton_27.setText(QCoreApplication.translate("Dialog", "P", None))
            self.pushButton_28.setText(
                QCoreApplication.translate("Dialog", "Enter", None)
            )
            self.pushButton_25.setText(QCoreApplication.translate("Dialog", "L", None))
            self.pushButton_29.setText(QCoreApplication.translate("Dialog", "K", None))
            self.pushButton_30.setText(QCoreApplication.translate("Dialog", "S", None))
            self.pushButton_31.setText(QCoreApplication.translate("Dialog", "H", None))
            self.pushButton_32.setText(QCoreApplication.translate("Dialog", "F", None))
            self.pushButton_33.setText(QCoreApplication.translate("Dialog", "J", None))
            self.pushButton_34.setText(QCoreApplication.translate("Dialog", "D", None))
            self.pushButton_35.setText(QCoreApplication.translate("Dialog", "A", None))
            self.pushButton_36.setText(QCoreApplication.translate("Dialog", "G", None))
            self.pushButton_37.setText(QCoreApplication.translate("Dialog", "X", None))
            self.pushButton_38.setText(QCoreApplication.translate("Dialog", "V", None))
            self.pushButton_39.setText(QCoreApplication.translate("Dialog", "M", None))
            self.pushButton_40.setText(QCoreApplication.translate("Dialog", "C", None))
            self.pushButton_41.setText(QCoreApplication.translate("Dialog", ",", None))
            self.pushButton_42.setText(QCoreApplication.translate("Dialog", ".", None))
            self.pushButton_43.setText(QCoreApplication.translate("Dialog", "Z", None))
            self.pushButton_44.setText(QCoreApplication.translate("Dialog", "B", None))
            self.pushButton_45.setText(QCoreApplication.translate("Dialog", "N", None))

            self.pushButton_5.setStyleSheet(  # Khi nhấn nút Shift đổi và giữ  màu nút#
                "background-color: rgb(190, 190, 190);\n"
                "color: rgb(0, 0, 0);\n"
                "border-radius: 10px;"
            )

    # this will emit when user long press on < button
    def long_press_timeout(self):
        print("long press event")  # Action to perform for long press event
        self.output = ""
        self.label.setText("")
        self.LNEDT.setText(self.output)

    def keyPressEvent(self, event: QKeyEvent):
        # Handle key press event
        if event.key() == Qt.Key_Escape:
            self.close()
        else:
            super().keyPressEvent(event)
